#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /src
COPY ["src/zbw.Auftragsverwaltung.BlazorApp/zbw.Auftragsverwaltung.BlazorApp.csproj", "zbw.Auftragsverwaltung.BlazorApp/"]
COPY ["src/zbw.Auftragsverwaltung.Domain/zbw.Auftragsverwaltung.Domain.csproj", "zbw.Auftragsverwaltung.Domain/"]
COPY ["src/zbw.Auftragsverwaltung.Client/zbw.Auftragsverwaltung.Client.csproj", "zbw.Auftragsverwaltung.Client/"]
COPY ["src/Lib/zbw.Auftragsverwaltung.Lib.HttpClient/zbw.Auftragsverwaltung.Lib.HttpClient.csproj", "Lib/zbw.Auftragsverwaltung.Lib.HttpClient/"]
COPY ["src/Lib/zbw.Auftragsverwaltung.Lib.ErrorHandling/zbw.Auftragsverwaltung.Lib.ErrorHandling.csproj", "Lib/zbw.Auftragsverwaltung.Lib.ErrorHandling/"]

RUN dotnet restore "zbw.Auftragsverwaltung.BlazorApp/zbw.Auftragsverwaltung.BlazorApp.csproj"
COPY . .
WORKDIR "/src/zbw.Auftragsverwaltung.BlazorApp"
RUN dotnet build "zbw.Auftragsverwaltung.BlazorApp.csproj" -c Release -o /app/build

FROM build-env AS publish
RUN dotnet publish "zbw.Auftragsverwaltung.BlazorApp.csproj" -c Release -o /app/publish

FROM nginx:alpine as final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot /usr/local/webapp/nginx/html
COPY src/zbw.Auftragsverwaltung.BlazorApp/nginx.conf /etc/nginx/nginx.conf
ENTRYPOINT ["dotnet", "zbw.Auftragsverwaltung.BlazorApp.dll"]